Repository UoB-HPC/SimEng, pull requests merged in 2021-10, with the labels that each got.

#191 Optimizations
  CMakeLists.txt
  src/include/simeng/AlwaysNotTakenPredictor.hh
  src/include/simeng/BTBPredictor.hh
  src/include/simeng/BTB_BWTPredictor.hh
  src/include/simeng/BranchPredictor.hh
  src/include/simeng/Instruction.hh
  src/include/simeng/ModelConfig.hh
  src/include/simeng/Pool.hh
  src/include/simeng/RegisterValue.hh
  src/include/simeng/arch/aarch64/Instruction.hh
  src/include/simeng/kernel/Linux.hh
  src/include/simeng/models/outoforder/Core.hh
  src/include/simeng/pipeline/A64FXPortAllocator.hh
  src/include/simeng/pipeline/BalancedPortAllocator.hh
  src/include/simeng/pipeline/DispatchIssueUnit.hh
  src/include/simeng/pipeline/ExecuteUnit.hh
  src/include/simeng/pipeline/PortAllocator.hh
  src/lib/AlwaysNotTakenPredictor.cc
  src/lib/BTBPredictor.cc
  src/lib/BTB_BWTPredictor.cc
  src/lib/ModelConfig.cc
  src/lib/RegisterValue.cc
  src/lib/arch/aarch64/Architecture.cc
  src/lib/arch/aarch64/Instruction.cc
  src/lib/arch/aarch64/Instruction_address.cc
  src/lib/arch/aarch64/Instruction_execute.cc
  src/lib/kernel/Linux.cc
  src/lib/models/outoforder/Core.cc
  src/lib/pipeline/A64FXPortAllocator.cc
  src/lib/pipeline/BalancedPortAllocator.cc
  src/lib/pipeline/DispatchIssueUnit.cc
  src/lib/pipeline/ExecuteUnit.cc
  src/lib/pipeline/LoadStoreQueue.cc
  test/unit/CMakeLists.txt
  test/unit/MockBranchPredictor.hh
  test/unit/MockInstruction.hh
  test/unit/PoolTest.cc
  test/unit/RegisterValueTest.cc
Labels: performance

#192 Bug fixes
  src/lib/arch/aarch64/Architecture.cc
  src/lib/arch/aarch64/InstructionMetadata.cc
  src/lib/arch/aarch64/Instruction_execute.cc
  src/lib/pipeline/FetchUnit.cc
  src/lib/pipeline/ReorderBuffer.cc
  test/regression/aarch64/instructions/misc.cc
  test/unit/CMakeLists.txt
  test/unit/ShiftValueTest.cc
Labels: bug

#195 CloverLeaf and TeaLeaf Benchmark Support
  src/include/simeng/arch/aarch64/Instruction.hh
  src/include/simeng/kernel/Linux.hh
  src/lib/arch/aarch64/Architecture.cc
  src/lib/arch/aarch64/ExceptionHandler.cc
  src/lib/arch/aarch64/InstructionMetadata.cc
  src/lib/arch/aarch64/Instruction_address.cc
  src/lib/arch/aarch64/Instruction_decode.cc
  src/lib/arch/aarch64/Instruction_execute.cc
  src/lib/kernel/Linux.cc
  src/lib/pipeline/RegisterAliasTable.cc
  test/regression/aarch64/Syscall.cc
  test/regression/aarch64/instructions/comparison.cc
  test/regression/aarch64/instructions/float.cc
  test/regression/aarch64/instructions/load.cc
  test/regression/aarch64/instructions/neon.cc
  test/regression/aarch64/instructions/sve.cc
Labels: enhancement

#197 Minifmm support
  src/lib/arch/aarch64/Instruction_address.cc
  src/lib/arch/aarch64/Instruction_execute.cc
  test/regression/aarch64/instructions/load.cc
  test/regression/aarch64/instructions/neon.cc
  test/regression/aarch64/instructions/store.cc
Labels: enhancement
