Repository UoB-HPC/SimEng, pull requests merged in 2021-12, with the labels that each got.

#199 Further AArch64 coverage targeting the CloverLeaf benchmark
  src/lib/arch/aarch64/InstructionMetadata.cc
  src/lib/arch/aarch64/Instruction_execute.cc
  src/lib/kernel/LinuxProcess.cc
  test/regression/aarch64/instructions/neon.cc
  test/regression/aarch64/instructions/sve.cc
Labels: enhancement

#201 Further AArch64 Support & Syscall OS Nuance Fixes
  CMakeLists.txt
  docs/requirements.txt
  src/include/simeng/Instruction.hh
  src/include/simeng/arch/aarch64/Instruction.hh
  src/include/simeng/kernel/Linux.hh
  src/lib/CMakeLists.txt
  src/lib/arch/aarch64/Architecture.cc
  src/lib/arch/aarch64/ExceptionHandler.cc
  src/lib/arch/aarch64/Instruction.cc
  src/lib/arch/aarch64/InstructionMetadata.cc
  src/lib/arch/aarch64/InstructionMetadata.hh
  src/lib/arch/aarch64/Instruction_address.cc
  src/lib/arch/aarch64/Instruction_decode.cc
  src/lib/arch/aarch64/Instruction_execute.cc
  src/lib/kernel/Linux.cc
  test/regression/aarch64/Syscall.cc
  test/regression/aarch64/instructions/arithmetic.cc
  test/regression/aarch64/instructions/neon.cc
  test/regression/aarch64/instructions/sve.cc
  test/unit/CMakeLists.txt
  test/unit/ShiftValueTest.cc
Labels: enhancement

#206 Improved Special Files Support
  .gitignore
  configs/a64fx.yaml
  configs/tx2.yaml
  simeng-fileio-test.txt
  src/include/simeng/ModelConfig.hh
  src/include/simeng/SpecialFileDirGen.hh
  src/include/simeng/kernel/Linux.hh
  src/include/simeng/kernel/LinuxProcess.hh
  src/lib/CMakeLists.txt
  src/lib/FlatMemoryInterface.cc
  src/lib/ModelConfig.cc
  src/lib/SpecialFileDirGen.cc
  src/lib/arch/aarch64/ExceptionHandler.cc
  src/lib/arch/aarch64/Instruction_execute.cc
  src/lib/kernel/Linux.cc
  src/lib/kernel/LinuxProcess.cc
  src/lib/kernel/specialFiles/online
  src/tools/simeng/main.cc
  test/regression/RegressionTest.cc
  test/regression/aarch64/AArch64RegressionTest.hh
  test/regression/aarch64/Syscall.cc
  test/regression/aarch64/instructions/sve.cc
Labels: bug, enhancement, performance

#207 Documentation update for 0.9.1 release
  CMakeLists.txt
  CONTRIBUTORS.txt
  Dockerfile
  RELEASE-NOTES.txt
  docs/sphinx/user/configuring_simeng.rst
  docs/sphinx/user/creating_binaries.rst
Labels: docs
