Repository UoB-HPC/SimEng, pull requests merged in 2022-09, with the labels that each got.

#246 Updated jenkins armclang build script to use new armclang22 compiler
  .jenkins/build_arm22.sh
Labels: tests

#235 Added checks in all processExceptionHandler functions to prohibit pro…
  src/lib/models/emulation/Core.cc
  src/lib/models/inorder/Core.cc
  src/lib/models/outoforder/Core.cc
Labels: bug

#242 Added comments explaining ELF File structure to Elf.cc file.
  src/lib/Elf.cc
Labels: docs

#233 Additional aarch64 and syscall support
  src/include/simeng/arch/aarch64/Instruction.hh
  src/include/simeng/arch/aarch64/helpers/neon.hh
  src/lib/arch/aarch64/ExceptionHandler.cc
  src/lib/arch/aarch64/InstructionMetadata.cc
  src/lib/arch/aarch64/Instruction_address.cc
  src/lib/arch/aarch64/Instruction_execute.cc
  test/regression/aarch64/Syscall.cc
  test/regression/aarch64/instructions/load.cc
  test/regression/aarch64/instructions/neon.cc
Labels: enhancement

#245 M1 Firestorm model
  configs/m1_firestorm.yaml
  src/include/simeng/pipeline/M1PortAllocator.hh
  src/lib/CMakeLists.txt
  src/lib/pipeline/M1PortAllocator.cc
Labels: enhancement

#240 Minor Feature Fixes
  src/include/simeng/Core.hh
  src/include/simeng/ModelConfig.hh
  src/include/simeng/SpecialFileDirGen.hh
  src/include/simeng/arch/Architecture.hh
  src/include/simeng/arch/aarch64/Architecture.hh
  src/include/simeng/arch/aarch64/helpers/auxiliaryFunctions.hh
  src/include/simeng/arch/aarch64/helpers/sve.hh
  src/include/simeng/models/emulation/Core.hh
  src/include/simeng/models/inorder/Core.hh
  src/include/simeng/models/outoforder/Core.hh
  src/include/simeng/version.hh.in
  src/lib/GenericPredictor.cc
  src/lib/ModelConfig.cc
  src/lib/arch/aarch64/Architecture.cc
  src/lib/arch/aarch64/Instruction_execute.cc
  src/lib/models/emulation/Core.cc
  src/lib/models/inorder/Core.cc
  src/lib/models/outoforder/Core.cc
  src/lib/pipeline/LoadStoreQueue.cc
  src/tools/simeng/main.cc
  test/regression/aarch64/AArch64RegressionTest.hh
  test/regression/aarch64/SystemRegisters.cc
  test/unit/GenericPredictorTest.cc
  test/unit/ISATest.cc
  test/unit/MockArchitecture.hh
Labels: bug

#239 Capstone update
  CMakeLists.txt
  src/include/simeng/arch/aarch64/MicroDecoder.hh
  src/include/simeng/arch/aarch64/helpers/sve.hh
  src/lib/CMakeLists.txt
  src/lib/Instruction.cc
  src/lib/arch/aarch64/InstructionMetadata.cc
  src/lib/arch/aarch64/Instruction_address.cc
  src/lib/arch/aarch64/Instruction_decode.cc
  src/lib/arch/aarch64/Instruction_execute.cc
  src/lib/arch/aarch64/MicroDecoder.cc
Labels: enhancement

#243 Process Image memory optimisation for SimEng [WIP]
  src/include/simeng/Elf.hh
  src/include/simeng/kernel/LinuxProcess.hh
  src/lib/Elf.cc
  src/lib/kernel/LinuxProcess.cc
  src/tools/simeng/main.cc
  test/regression/RegressionTest.cc
Labels: performance

#247 New core creation
  configs/a64fx.yaml
  configs/m1_firestorm.yaml
  configs/tx2.yaml
  src/include/simeng/BranchPredictor.hh
  src/include/simeng/CoreInstance.hh
  src/include/simeng/MemoryInterface.hh
  src/include/simeng/ModelConfig.hh
  src/include/simeng/arch/Architecture.hh
  src/include/simeng/arch/aarch64/Instruction.hh
  src/include/simeng/models/inorder/Core.hh
  src/include/simeng/pipeline/FetchUnit.hh
  src/include/simeng/pipeline/LoadStoreQueue.hh
  src/lib/CMakeLists.txt
  src/lib/CoreInstance.cc
  src/lib/ModelConfig.cc
  src/lib/models/inorder/Core.cc
  src/lib/models/outoforder/Core.cc
  src/tools/simeng/main.cc
  test/regression/aarch64/AArch64RegressionTest.hh
Labels: bug, enhancement

#249 Output prefix
  .jenkins/build_test_run.sh
  src/lib/CoreInstance.cc
  src/lib/ModelConfig.cc
  src/lib/arch/aarch64/Architecture.cc
  src/lib/arch/aarch64/ExceptionHandler.cc
  src/lib/arch/aarch64/Instruction_execute.cc
  src/lib/kernel/Linux.cc
  src/lib/kernel/LinuxProcess.cc
  src/lib/models/emulation/Core.cc
  src/lib/models/inorder/Core.cc
  src/lib/models/outoforder/Core.cc
  src/tools/simeng/main.cc
  test/regression/aarch64/Exception.cc
Labels: enhancement
