Repository UoB-HPC/SimEng, pull requests merged in 2023-12, with the labels that each got.

#303 RISC-V Single and Double Precision Floating Point extension
  CMakeLists.txt
  configs/DEMO_RISCV.yaml
  configs/sst-cores/a64fx-sst.yaml
  docs/sphinx/assets/instruction_groups_RISCV.png
  docs/sphinx/developer/arch/supported/aarch64.rst
  docs/sphinx/developer/arch/supported/riscv.rst
  src/include/simeng/CoreInstance.hh
  src/include/simeng/FixedLatencyMemoryInterface.hh
  src/include/simeng/FlatMemoryInterface.hh
  src/include/simeng/Instruction.hh
  src/include/simeng/MemoryInterface.hh
  src/include/simeng/RegisterValue.hh
  src/include/simeng/arch/aarch64/Instruction.hh
  src/include/simeng/arch/aarch64/MicroDecoder.hh
  src/include/simeng/arch/aarch64/helpers/float.hh
  src/include/simeng/arch/riscv/Architecture.hh
  src/include/simeng/arch/riscv/Instruction.hh
  src/include/simeng/arch/riscv/InstructionGroups.hh
  src/include/simeng/pipeline/ReorderBuffer.hh
  src/lib/CoreInstance.cc
  src/lib/GenericPredictor.cc
  src/lib/ModelConfig.cc
  src/lib/arch/aarch64/Architecture.cc
  src/lib/arch/aarch64/ExceptionHandler.cc
  src/lib/arch/aarch64/Instruction.cc
  src/lib/arch/aarch64/InstructionMetadata.cc
  src/lib/arch/aarch64/InstructionMetadata.hh
  src/lib/arch/aarch64/Instruction_address.cc
  src/lib/arch/aarch64/Instruction_decode.cc
  src/lib/arch/aarch64/Instruction_execute.cc
  src/lib/arch/riscv/Architecture.cc
  src/lib/arch/riscv/ExceptionHandler.cc
  src/lib/arch/riscv/Instruction.cc
  src/lib/arch/riscv/InstructionMetadata.cc
  src/lib/arch/riscv/InstructionMetadata.hh
  src/lib/arch/riscv/Instruction_address.cc
  src/lib/arch/riscv/Instruction_decode.cc
  src/lib/arch/riscv/Instruction_execute.cc
  src/lib/kernel/LinuxProcess.cc
  src/lib/models/emulation/Core.cc
  src/lib/models/inorder/Core.cc
  src/lib/models/outoforder/Core.cc
  src/lib/pipeline/A64FXPortAllocator.cc
  src/lib/pipeline/DispatchIssueUnit.cc
  src/lib/pipeline/FetchUnit.cc
  src/lib/pipeline/LoadStoreQueue.cc
  src/lib/pipeline/RenameUnit.cc
  src/tools/simeng/main.cc
  sst/config/a64fx-config.py
  test/regression/aarch64/LoadStoreQueue.cc
  test/regression/aarch64/Syscall.cc
  test/regression/aarch64/instructions/bitmanip.cc
  test/regression/riscv/CMakeLists.txt
  test/regression/riscv/LoadStoreQueue.cc
  test/regression/riscv/RISCVRegressionTest.hh
  test/regression/riscv/Syscall.cc
  test/regression/riscv/instructions/float.cc
  test/unit/MockInstruction.hh
  test/unit/pipeline/A64FXPortAllocatorTest.cc
Labels: enhancement

#363 Register bug fixes
  src/include/simeng/RegisterFileSet.hh
  src/include/simeng/arch/aarch64/helpers/sve.hh
  src/lib/arch/aarch64/Instruction_execute.cc
  src/lib/pipeline/RegisterAliasTable.cc
  src/lib/pipeline/ReorderBuffer.cc
  test/regression/RegressionTest.cc
  test/regression/aarch64/instructions/sve.cc
Labels: bug, tests, 0.9.6

#364 Correct CSRRW State Change
  src/lib/arch/riscv/ExceptionHandler.cc
  src/lib/arch/riscv/Instruction_execute.cc
Labels: bug, 0.9.6
