Repository UoB-HPC/SimEng, pull requests merged in 2024-02, with the labels that each got.

#381 Added fix for returning a consistent nan value from a divide by zero
  src/include/simeng/arch/aarch64/helpers/neon.hh
  src/include/simeng/arch/aarch64/helpers/sve.hh
  src/lib/arch/aarch64/Instruction_execute.cc
  test/regression/aarch64/instructions/float.cc
  test/unit/aarch64/InstructionTest.cc
Labels: bug, tests, 0.9.6

#383 st1w dirtied memory fix
  src/lib/kernel/LinuxProcess.cc
Labels: bug, tests, 0.9.6

#370 Config file bug cleanup
  src/include/simeng/arch/Architecture.hh
  src/include/simeng/arch/aarch64/Architecture.hh
  src/include/simeng/arch/riscv/Architecture.hh
  src/include/simeng/pipeline/FetchUnit.hh
  src/lib/arch/aarch64/Architecture.cc
  src/lib/arch/riscv/Architecture.cc
  src/lib/config/ModelConfig.cc
  src/lib/models/emulation/Core.cc
  src/lib/pipeline/FetchUnit.cc
  test/regression/aarch64/Exception.cc
  test/unit/MockArchitecture.hh
  test/unit/aarch64/ArchitectureTest.cc
Labels: bug, 0.9.6

#388 Fix broken tests caused by config-bug-fixes PR
  src/lib/config/ModelConfig.cc
  test/integration/ConfigTest.cc
  test/regression/riscv/RISCVRegressionTest.hh
Labels: bug, 0.9.6

#377 Name changes
  docs/sphinx/developer/arch/supported/aarch64.rst
  docs/sphinx/developer/arch/supported/riscv.rst
  src/include/simeng/RegisterValue.hh
  src/include/simeng/arch/aarch64/Architecture.hh
  src/include/simeng/arch/aarch64/ExceptionHandler.hh
  src/include/simeng/arch/aarch64/Instruction.hh
  src/include/simeng/arch/aarch64/InstructionGroups.hh
  src/include/simeng/arch/aarch64/MicroDecoder.hh
  src/include/simeng/arch/riscv/Architecture.hh
  src/include/simeng/arch/riscv/ExceptionHandler.hh
  src/include/simeng/arch/riscv/Instruction.hh
  src/include/simeng/arch/riscv/InstructionGroups.hh
  src/include/simeng/config/ExpectationNode.hh
  src/include/simeng/kernel/LinuxProcess.hh
  src/lib/arch/aarch64/Architecture.cc
  src/lib/arch/aarch64/ExceptionHandler.cc
  src/lib/arch/aarch64/Instruction.cc
  src/lib/arch/aarch64/Instruction_address.cc
  src/lib/arch/aarch64/Instruction_decode.cc
  src/lib/arch/aarch64/Instruction_execute.cc
  src/lib/arch/aarch64/MicroDecoder.cc
  src/lib/arch/riscv/Architecture.cc
  src/lib/arch/riscv/ExceptionHandler.cc
  src/lib/arch/riscv/Instruction.cc
  src/lib/arch/riscv/Instruction_address.cc
  src/lib/arch/riscv/Instruction_decode.cc
  src/lib/arch/riscv/Instruction_execute.cc
  src/lib/config/ModelConfig.cc
  src/lib/kernel/Linux.cc
  src/lib/kernel/LinuxProcess.cc
  test/regression/RegressionTest.cc
  test/regression/aarch64/MicroOperation.cc
  test/regression/aarch64/SmokeTest.cc
  test/regression/aarch64/instructions/comparison.cc
  test/regression/aarch64/instructions/load.cc
  test/regression/aarch64/instructions/sme.cc
  test/regression/aarch64/instructions/store.cc
  test/regression/aarch64/instructions/sve.cc
  test/regression/riscv/Syscall.cc
  test/regression/riscv/instructions/store.cc
  test/unit/OSTest.cc
  test/unit/ProcessTest.cc
  test/unit/aarch64/ExceptionHandlerTest.cc
  test/unit/riscv/ExceptionHandlerTest.cc
Labels: enhancement, docs, code consistency, 0.9.6

#385 Architecture Class cleanup
  src/include/simeng/Instruction.hh
  src/include/simeng/arch/Architecture.hh
  src/include/simeng/arch/aarch64/Architecture.hh
  src/include/simeng/arch/aarch64/Instruction.hh
  src/include/simeng/arch/riscv/Architecture.hh
  src/include/simeng/arch/riscv/Instruction.hh
  src/lib/arch/aarch64/Architecture.cc
  src/lib/arch/riscv/Architecture.cc
  src/lib/arch/riscv/Instruction.cc
  test/unit/MockArchitecture.hh
  test/unit/aarch64/InstructionTest.cc
  test/unit/pipeline/FetchUnitTest.cc
  test/unit/riscv/InstructionTest.cc
Labels: code consistency, 0.9.6

#389 Instruction Class Clean-Up
  docs/sphinx/developer/arch/supported/aarch64.rst
  docs/sphinx/developer/arch/supported/riscv.rst
  src/include/simeng/Instruction.hh
  src/include/simeng/arch/aarch64/Instruction.hh
  src/include/simeng/arch/aarch64/helpers/arithmetic.hh
  src/include/simeng/arch/aarch64/helpers/bitmanip.hh
  src/include/simeng/arch/aarch64/helpers/comparison.hh
  src/include/simeng/arch/aarch64/helpers/conditional.hh
  src/include/simeng/arch/aarch64/helpers/divide.hh
  src/include/simeng/arch/aarch64/helpers/float.hh
  src/include/simeng/arch/aarch64/helpers/logical.hh
  src/include/simeng/arch/aarch64/helpers/multiply.hh
  src/include/simeng/arch/aarch64/helpers/neon.hh
  src/include/simeng/arch/aarch64/helpers/sve.hh
  src/include/simeng/arch/aarch64/operandContainer.hh
  src/include/simeng/arch/riscv/Instruction.hh
  src/lib/CMakeLists.txt
  src/lib/Instruction.cc
  src/lib/arch/aarch64/Instruction.cc
  src/lib/arch/aarch64/Instruction_decode.cc
  src/lib/arch/aarch64/Instruction_execute.cc
  src/lib/arch/riscv/Instruction.cc
  src/lib/arch/riscv/Instruction_address.cc
  src/lib/arch/riscv/Instruction_decode.cc
  test/regression/aarch64/AArch64RegressionTest.hh
  test/unit/CMakeLists.txt
  test/unit/MockInstruction.hh
  test/unit/aarch64/OperandContainerTest.cc
  test/unit/riscv/InstructionTest.cc
Labels: code consistency, 0.9.6

#379 System call and exception regression tests
  docs/sphinx/developer/arch/supported/aarch64.rst
  docs/sphinx/developer/test/index.rst
  docs/sphinx/user/running_simeng.rst
  src/include/simeng/kernel/Linux.hh
  src/lib/arch/aarch64/ExceptionHandler.cc
  src/lib/arch/riscv/ExceptionHandler.cc
  src/lib/config/ModelConfig.cc
  src/lib/kernel/Linux.cc
  src/lib/kernel/LinuxProcess.cc
  test/regression/aarch64/AArch64RegressionTest.cc
  test/regression/aarch64/AArch64RegressionTest.hh
  test/regression/aarch64/CMakeLists.txt
  test/regression/aarch64/Exception.cc
  test/regression/aarch64/Syscall.cc
  test/regression/aarch64/data/truncate-test.txt
  test/regression/riscv/CMakeLists.txt
  test/regression/riscv/Exception.cc
  test/regression/riscv/RISCVRegressionTest.cc
  test/regression/riscv/RISCVRegressionTest.hh
  test/regression/riscv/Syscall.cc
  test/regression/riscv/data/truncate-test.txt
  test/unit/ProcessTest.cc
  test/unit/aarch64/ExceptionHandlerTest.cc
  test/unit/riscv/ExceptionHandlerTest.cc
Labels: tests, 0.9.6

#368 RISC-V Compressed Instructions
  configs/DEMO_RISCV.yaml
  docs/sphinx/developer/arch/supported/riscv.rst
  docs/sphinx/user/configuring_simeng.rst
  src/include/simeng/arch/Architecture.hh
  src/include/simeng/arch/aarch64/Architecture.hh
  src/include/simeng/arch/aarch64/Instruction.hh
  src/include/simeng/arch/riscv/ArchInfo.hh
  src/include/simeng/arch/riscv/Architecture.hh
  src/include/simeng/arch/riscv/Instruction.hh
  src/include/simeng/kernel/LinuxProcess.hh
  src/include/simeng/pipeline/FetchUnit.hh
  src/lib/arch/aarch64/Architecture.cc
  src/lib/arch/riscv/Architecture.cc
  src/lib/arch/riscv/ExceptionHandler.cc
  src/lib/arch/riscv/InstructionMetadata.cc
  src/lib/arch/riscv/InstructionMetadata.hh
  src/lib/arch/riscv/Instruction_address.cc
  src/lib/arch/riscv/Instruction_decode.cc
  src/lib/arch/riscv/Instruction_execute.cc
  src/lib/config/ModelConfig.cc
  src/lib/pipeline/FetchUnit.cc
  test/regression/riscv/CMakeLists.txt
  test/regression/riscv/RISCVRegressionTest.cc
  test/regression/riscv/RISCVRegressionTest.hh
  test/regression/riscv/instructions/compressed.cc
  test/regression/riscv/instructions/jump.cc
  test/unit/MockArchitecture.hh
  test/unit/pipeline/FetchUnitTest.cc
  test/unit/riscv/ArchitectureTest.cc
Labels: enhancement, 0.9.7

#392 Added conditional existence checks before early config option querying
  src/lib/config/ModelConfig.cc
Labels: bug, 0.9.6

#395 AArch64 bitfieldManipulate bounds checking
  src/include/simeng/arch/aarch64/helpers/auxiliaryFunctions.hh
  test/unit/aarch64/AuxiliaryFunctionsTest.cc
Labels: bug, 0.9.6

#396 0.9.6 update
  .circleci/config.yml
  CMakeLists.txt
  CONTRIBUTORS.txt
  RELEASE-NOTES.txt
  docs/requirements.txt
  docs/sphinx/index.rst
  src/lib/arch/riscv/Instruction_execute.cc
  test/integration/ConfigTest.cc
Labels: docs, 0.9.6
